### ISSUE TITLE
ModuleNotFoundError: No module named 'playwright._impl._api_types'

### ISSUE THREAD

**Issue by HuaJiShooter** [Well2333/nonebot-plugin-bilichat#184]
### 操作系统

Windows

### Python 版本

3.12.2

### NoneBot 版本

1.3.1

### Bilichat 版本

3.2.0

### 描述问题

Bilichat和playwright均为最新版本，加载Bilichat时报错。

### 截图或日志

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Code\Python\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot_plugin_bilichat\__init__.py", line 8, in <module>
    from . import adatpters
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot_plugin_bilichat\adatpters\__init__.py", line 11, in <module>
    from ..content import Column, Dynamic, Video
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot_plugin_bilichat\content\__init__.py", line 2, in <module>
    from .dynamic import Dynamic
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot_plugin_bilichat\content\dynamic.py", line 4, in <module>
    from ..lib.draw.dynamic import draw_dynamic
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot_plugin_bilichat\lib\draw\dynamic\__init__.py", line 6, in <module>
    from .browser_shot import screenshot as draw_dynamic
  File "C:\Code\nonebot\QQbot\.venv\Lib\site-packages\nonebot_plugin_bilichat\lib\draw\dynamic\browser_shot.py", line 10, in <module>
    from playwright._impl._api_types import TimeoutError

**Comment by LoCCai** [comment]
playwright要低版本的，我往下试了1.20可以

**Comment by Well2333** [comment]
playwright 组件由 nonebot_plugin_htmlrender 提供，如果加载时出现 playwright 的异常可以尝试检查 nonebot_plugin_htmlrender 是否能够被单独加载

**Comment by HuaJiShooter** [comment]
nonebot_plugin_htmlrender组件可以加载
![1ca71ec8541a4d86542f412aaf49997c](https://github.com/Well2333/nonebot-plugin-bilichat/assets/111669935/d5344fea-9311-42f6-b197-2c5c6717800c)

**Comment by Well2333** [comment]
此 issue 由于长期不活跃，现将其关闭，如果您的问题没有解决，请在此 issue 下留言

**Comment by QianFuv** [comment]
相同问题出现，卸载 `bilichat` 后 `htmlrender` 可以正常加载，但是下载 `bilichat` 后提示 `ModuleNotFoundError: No module named 'playwright._impl._api_types'`

**Comment by Well2333** [comment]
> 相同问题出现，卸载 `bilichat` 后 `htmlrender` 可以正常加载，但是下载 `bilichat` 后提示 `ModuleNotFoundError: No module named 'playwright._impl._api_types'`

playwright版本是多少

**Comment by QianFuv** [comment]
> playwright 组件由 nonebot_plugin_htmlrender 提供，如果加载时出现 playwright 的异常可以尝试检查 nonebot_plugin_htmlrender 是否能够被单独加载

您不是说 `playwright` 是由 `nonebot_plugin_htmlrender` 提供吗

**Comment by Well2333** [comment]
> > playwright 组件由 nonebot_plugin_htmlrender 提供，如果加载时出现 playwright 的异常可以尝试检查 nonebot_plugin_htmlrender 是否能够被单独加载
> 
> 您不是说 `playwright` 是由 `nonebot_plugin_htmlrender` 提供吗

是的，但是htmlrender仅提供浏览器实例，具体的操作仍需要插件完成，因此不可避免的需要引入playwright的对象，如果playwright版本更新后对应的对象可能会被移除或移动，或过老版本的playwright可能不包含对应的对象，所以需要具体playwright来解决问题

**Comment by QianFuv** [comment]
我使用 `pip list` 查看到 `playwright` 的版本为 `1.43.0`
