### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by mcxiaochenn** [Well2333/nonebot-plugin-bilichat#222]
### 操作系统

Windows

### Python 版本

3.11

### NoneBot 版本

2

### Bilichat 版本

new

### 描述问题

报错

关闭插件后可正常运行

### 插件的配置项

```
# 对同一视频的响应冷却时间(防止刷屏)
bilichat_cd_time = 120
# 网络请求重试次数
bilichat_neterror_retry = 3
# 是否使用浏览器截图(需要额外依赖)
bilichat_use_browser = True

# 是否开启词云(需要额外依赖)
bilichat_word_cloud = True

# === AI 总结相关 ===
# 官方总结接口
bilichat_official_summary = True
```

### 截图或日志

```
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_connection.py:265> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 272, in run
    await self._transport.connect()
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 223, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
05-19 21:52:31 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\starlette\routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 38, in init
    browser = await get_browser(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 61, in get_browser
    return _browser if _browser and _browser.is_connected() else await init(**kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 32, in init
    _playwright = await async_playwright().start()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\nonebot\New-QQ-Bot2\.venv\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 223, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

05-19 21:52:31 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by Well2333** [comment]
请检查playwright是否正常安装，并且请提供详细的playwright版本号及nonebot-plugin-htmlrender版本号

**Comment by mcxiaochenn** [comment]
抱歉，偷懒已换类似项目，有缘再相会
