### ISSUE TITLE
Bug: QRCode登录问题

### ISSUE THREAD

**Issue by Yppup** [Well2333/nonebot-plugin-bilichat#262]
### 操作系统

Linux

### Python 版本

3.11.2

### NoneBot 版本

2.3.3

### Bilichat 版本

5.13.2

### 描述问题

获取登录QRCode报错，使用pipx安装pypng后仍然报错。

### 截图或日志

```
10-27 23:17:46 [SUCCESS] nonebot | OneBot V11 3782204632 | [message.private.friend]: Message XXXXXXXXX from XXXXXXXX 'qrlogin'
10-27 23:17:46 [DEBUG] nonebot | Checking for matchers in priority 1...
10-27 23:17:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bilichat.commands.login, lineno=56)
10-27 23:17:46 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_bilichat.commands.login, lineno=56)
10-27 23:17:46 [DEBUG] nonebot | Running handler Dependent(call=bili_qrcode_login)
10-27 23:17:46 [DEBUG] nonebot_plugin_bilichat | qrcode login url: XXXXXXXXXXXXXXXXXXXXXX
10-27 23:17:46 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bilichat.commands.login, lineno=56) running complete
10-27 23:17:46 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bilichat.commands.login, lineno=56) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/BiliBot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
  return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/nonebot_plugin_bilichat/commands/login.py", line 90, in bili_qrcode_login
    await UniMessage(Image(raw=await login.get_qrcode(qr_url))).send(target=target)  # type: ignore
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/bilireq/login/__init__.py", line 90, in get_qrcode
    img = qr.make_image(image_factory=PyPNGImage)
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/qrcode/main.py", line 368, in make_image
    im = image_factory(
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/qrcode/image/base.py", line 30, in __init__
    self._img = self.new_image(**kwargs)
  File "/root/BiliBot/.venv/lib/python3.11/site-packages/qrcode/image/pure.py", line 18, in new_image
    raise ImportError("PyPNG library not installed.")
ImportError: PyPNG library not installed.
```

**Comment by Well2333** [comment]
项目依赖中包含 qrcode 包，该包依赖于 pypng 包，因此没有在 pyproject.toml 中直接声明。

您可以尝试完整删除虚拟环境（包括对应的 lock）后重新安装，如果能够稳定复现，请您提供您使用的安装方式、lock 文件、环境内容等虚拟环境相关信息。

顺便一提，pipx 是为 cli 特化的管理器， 安装的每个包都是处于独立的环境中，仅包含依赖以及其自身，而不是常规的包管理器，请您了解 pipx 的具体用途后再进行使用，以免出现此类问题。

**Comment by Yppup** [comment]
> 项目依赖中包含 qrcode 包，该包依赖于 pypng 包，因此没有在 pyproject.toml 中直接声明。
> 
> 您可以尝试完整删除虚拟环境（包括对应的 lock）后重新安装，如果能够稳定复现，请您提供您使用的安装方式、lock 文件、环境内容等虚拟环境相关信息。
> 
> 顺便一提，pipx 是为 cli 特化的管理器， 安装的每个包都是处于独立的环境中，仅包含依赖以及其自身，而不是常规的包管理器，请您了解 pipx 的具体用途后再进行使用，以免出现此类问题。

最近应该是没有什么时间再折腾了，打算用手动添加cookie路径的方式，但出现value_error，保存cookie的文件使用UTF-8编码，请问cookie的存放是否有格式要求，比如仅写入特定的字段即可。

**Comment by Well2333** [comment]
grpc 的 cookies 需要小电视 app 抓包获取，您应该无法手动填写。

**Comment by Well2333** [comment]
grpc 的 cookies 需要小电视 app 抓包获取，您应该无法手动填写。

**Comment by hanasa2023** [comment]
该项目应该为qrcode添加可选依赖pypng，因为qrcode从7.5.0.dev开始不再将pypng作为默认依赖项，而是变更为了可选依赖。具体可参考：[commit dee7e1d](https://github.com/lincolnloop/python-qrcode/commit/dee7e1df78c66d1e37589473fd014bb2fe99f0bb)

**Comment by Well2333** [comment]
fixed #263
