### ISSUE TITLE
依赖中的httpx版本不兼容

### ISSUE THREAD

**Issue by Yppup** [Well2333/nonebot-plugin-bilichat#270]
### 操作系统

Linux

### Python 版本

3.11.2

### NoneBot 版本

2.4.1

### Bilichat 版本

5.13.4

### 描述问题

报错内容：
```
ImportError: cannot import name 'ProxiesTypes' from 'httpx._types' (/root/BiliBot/.venv/lib/python3.11/site-packages/httpx/_types.py)
```

似乎是上游bilireq请求库的问题，通过将虚拟环境中的httpx手动降级为0.28.0之前的版本解决。
详见：https://github.com/langchain-ai/langserve/issues/796#issuecomment-2511226034

**Comment by Yppup** [comment]
https://github.com/SK-415/bilireq/pull/32

**Comment by Well2333** [comment]
已了解，请耐心等待上游更新

**Comment by hakureireimusama** [comment]
更新之后日志如下，无法加载，httpx版本0.28.1，是不是也是楼主这个问题呢

01-05 18:03:57 [ERROR] nonebot | Failed to import "nonebot_plugin_bilichat"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot\plugin\load.py", line 133, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot\plugin\load.py", line 67, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 205, in load_all_plugins
    return set(
  File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\admini\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 257, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot_plugin_bilichat\__init__.py", line 71, in <module>
    from . import api, base_content_parsing, commands  # noqa: F401, E402
  File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot_plugin_bilichat\api\__init__.py", line 8, in <module>
    from . import bilibili_auth, subs_config  # noqa: F401
  File "C:\bot\xxm-bot\.venv\lib\site-packages\nonebot_plugin_bilichat\api\bilibili_auth.py", line 1, in <module>
    from bilireq.auth import Auth
  File "C:\bot\xxm-bot\.venv\lib\site-packages\bilireq\__init__.py", line 1, in <module>
    from .utils import get, post  # noqa
  File "C:\bot\xxm-bot\.venv\lib\site-packages\bilireq\utils\__init__.py", line 8, in <module>
    from httpx._types import HeaderTypes, ProxiesTypes, URLTypes
ImportError: cannot import name 'ProxiesTypes' from 'httpx._types' (C:\bot\xxm-bot\.venv\lib\site-packages\httpx\_types.py)

**Comment by hakureireimusama** [comment]
httpx 0.27.2 加载成功了

**Comment by Well2333** [comment]
了解到 bilireq 已合并针对此 issue 的修改，且 6.0 版本无需 bilireq，现关闭此 issue

**Comment by djkcyl** [comment]
![99e0c4d3b4324c9c668282a64bfd4674](https://github.com/user-attachments/assets/4c658140-69ed-44dd-ac1d-1fdc7c010a08)

**Comment by SK-415** [comment]
![image](https://github.com/user-attachments/assets/5019adf7-67f2-4416-bec7-734862a4e494)
