### ISSUE TITLE
KeyError bili_number

### ISSUE THREAD

**Issue by forchannot** [Well2333/nonebot-plugin-bilichat#30]
当发送up主个人空间时会出现KeyError bili_number
bilichat版本: 1.8.0
nb端收到的日志
```
04-29 16:24:17 [SUCCESS] nonebot | OneBot V11 2029172546 | [message.group.normal]: Message -1136853180 from 1492164106@[群:710768309] '&#91;&#91;分享&#93;联合国的个人空间&#93;请使用最新版本手机QQ查看[json:data={"app":"com.te
ncent.structmsg","desc":"新闻","bizsrc":"","view":"news...]'
```
gocq收到的日志
```
: &#91;&#91;分享&#93;联合国的个人空间&#93;请使用最新版本手机QQ查看[CQ:json,data={"app":"com.tencent.structmsg"&#44;"desc":"新闻"&#44;"bizsrc":""&#44;"view":"news"&#44;"ver":"0.0.0.1"&#44;"prompt":"&#91;分享&#93;联合国的个人空间"&#44;"meta":{"news":{"action":""&#44;"android_pkg_name":""&#44;"app_type":1&#44;"appid":100951776&#44;"ctime":1682756365&#44;"desc":"你感兴趣的视频都在B站"&#44;"jumpUrl":"https:\/\/b23.tv\/xrbcW36?share_medium=android&amp;share_source=qq&amp;bbid=XX8E8208EF0786F05E19485C7F78D671AD1EB&amp;ts=1682756360079"&#44;"preview":"https:\/\/pic.ugcimg.cn\/fb4fd72800eab6723105af744f9259b6\/jpg1"&#44;"source_icon":"https:\/\/open.gtimg.cn\/open\/app_icon\/00\/95\/17\/76\/100951776_100_m.png?t=1682411052"&#44;"source_url":""&#44;"tag":"哔哩哔哩"&#44;"title":"联合国的个人空间"&#44;"uin":2801303328}}&#44;"config":{"ctime":1682756365&#44;"forward":true&#44;"token":"dcf97000fe48fcc9a56cd659d3010e9c"&#44;"type":"normal"}}] (-1136853180)
```
报错信息如下
```
04-29 16:19:28 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bilichat) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LittlePaimon\bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_bilichat\__init__.py", line 122, in video_info
    bili_number, uid = state["bili_number"], state["_uid_"]
KeyError: 'bili_number'
```

**Comment by Well2333** [comment]
源消息是小程序还是链接？

**Comment by forchannot** [comment]
小程序

**Comment by forchannot** [comment]
![image](https://user-images.githubusercontent.com/100580891/235303297-8136fe88-6ca6-4cbe-9290-22d6ca5ab2e5.png)
而且这俩不同的反应还不同，你感兴趣的那个才会触发这个bug，另外一个不会，但是也没有返回结果，只会出现aps的warning
```
04-29 20:50:15 [SUCCESS] nonebot | OneBot V11 2029172546 | [message.group.normal]: Message -769589613 from xxxxxx@[群:xxxx] '[json:data={"app":"com.tencent.structmsg","con fig":{"ctime":1682772614,"forwar...]'
04-29 20:50:17 [WARNING] apscheduler | Run time of job "Scheduler.exec_fetch (trigger: interval[0:00:03], next run at: 2023-04-29 20:50:19 CST)" was missed by 0:00:01.544607
```
通过对比两个小程序分别的信息发现，你感兴趣那个jumpUrl的值为`b23.tv`开头的share链接，而另外一个是`space.bilibili.com`的域名
两个小程序完整的json信息分别为
你感兴趣：
```
{
    "app": "com.tencent.structmsg",
    "bizsrc": "",
    "config": {
        "ctime": 1682756365,
        "forward": true,
        "token": "dcf97000fe48fcc9a56cd659d3010e9c",
        "type": "normal"
    },
    "desc": "新闻",
    "meta": {
        "news": {
            "action": "",
            "android_pkg_name": "",
            "app_type": 1,
            "appid": 100951776,
            "ctime": 1682756365,
            "desc": "你感兴趣的视频都在B站",
            "jumpUrl": "https://b23.tv/xrbcW36?share_medium=android&amp;share_source=qq&amp;bbid=XX8E8208EF0786F05E19485C7F78D671AD1EB&amp;ts=1682756360079",
            "preview": "https://pic.ugcimg.cn/fb4fd72800eab6723105af744f9259b6/jpg1",
            "source_icon": "https://open.gtimg.cn/open/app_icon/00/95/17/76/100951776_100_m.png?t=1682411052",
            "source_url": "",
            "tag": "哔哩哔哩",
            "title": "联合国的个人空间",
            "uin": 2801303328
        }
    },
    "prompt": "&#91;分享&#93;联合国的个人空间",
    "ver": "0.0.0.1",
    "view": "news"
}

```
你我的共同世界
```
{
    "app": "com.tencent.structmsg",
    "bizsrc": "",
    "config": {
        "ctime": 1682772435,
        "forward": true,
        "token": "4b1de33be32f8e3641cd9a506234e33b",
        "type": "normal"
    },
    "desc": "新闻",
    "meta": {
        "news": {
            "action": "",
            "android_pkg_name": "",
            "app_type": 1,
            "appid": 100951776,
            "ctime": 1682772435,
            "desc": "你我的共同世界！",
            "jumpUrl": "https://space.bilibili.com/1649919642?share_session_id=ca99fa2e-b146-43f4-8e30-8e3bfb4267a6&amp;share_medium=android&amp;share_source=qq&amp;bbid=XU3DBD234141A8557D4C63A0EB2B82031E0DC&amp;ts=1682772432406",
            "preview": "https://pic.ugcimg.cn/fb4fd72800eab6723105af744f9259b6/jpg1",
            "source_icon": "https://open.gtimg.cn/open/app_icon/00/95/17/76/100951776_100_m.png?t=1682411052",
            "source_url": "",
            "tag": "哔哩哔哩",
            "title": "联合国的个人空间",
            "uin": 1492164106
        }
    },
    "prompt": "&#91;分享&#93;联合国的个人空间",
    "ver": "0.0.0.1",
    "view": "news"
}
```

**Comment by Well2333** [comment]
因为bilichat是使用正则匹配进行信息提取的，你可以发现报错的里面包含了一个b23的链接，没反应的是space.bilibili.com，因此前者会触发响应器，但是由于不是视频或者专栏，因此自然不会提取出av号bv号或者cv号，就报错了。

**Comment by Well2333** [comment]
另外，bilichat插件没有使用aps，你那个warning并不是bilichat造成的
